<a href="https://colab.research.google.com/github/CSP-GD/notes/blob/master/practice/tool/colab/%E5%BE%9Ecolab%E9%96%8B%E5%A7%8B%E5%AD%B8%E8%B5%B7dl/00/00.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

使用 Tensorflow v2  
導入 Tensorflow 與 Numpy

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np

print(tf.__version__)
print(np.__version__)

TensorFlow 2.x selected.
2.1.0
1.17.5


In [25]:
a = tf.constant([0,1,2,3],shape=[2,2])
b = tf.constant([2,5,2,7],shape=[2,2])
print(a+b)

tf.Tensor(
[[ 2  6]
 [ 4 10]], shape=(2, 2), dtype=int32)


In [24]:
@tf.function
def model(ws:[tf.Variable], x:tf.Tensor):
    y_pred = x
    for w in ws:
        y_pred = tf.matmul(w, y_pred)
    return y_pred

optimizer = tf.optimizers.Adam()

w = tf.Variable([[1.], [2.]])
x = tf.constant([[3., 4.]])
y_true = tf.multiply(x, 2.)

# i=10
# while(--i):
#     with tf.GradientTape() as tape:
#         loss = tf.losses.mean_squared_error(y_true,model(x,[w]))

#     gradients = tape.gradient(loss, [w])
#     optimizer.apply_gradients(zip(gradients, [w]))

# print(w)
model([w], x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [6., 8.]], dtype=float32)>